### ISSUE TITLE
Add support for Create / Edit / Delete Access Codes

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#236]
# Tasks:
#### `<AccessCodeForm />`:
- [ ] Create the "Access Code Form" component

#### `<AccessCodeTable />`:
- [ ] Add `disableCreate`, `disableEdit`, `disableDelete` props to the `AccessCodesTable` component
- [ ] Show `+` button when `disableCreate` is `false`
- [ ] Show "menu" button on Code row when `disableEdit` and `disableDelete` is `false`

#### `<AccessCodeDetails />`:
- [ ] Add `disableEdit` and `disableDelete` props to the `AccessCodeDetails` component

# Designs

### `<AccessCodeForm />`
```
interface AccessCodeFormProps {
    accessCodeId?: string        // when set, this component is used for editing
    onCreate?: (ac: AccessCode) => void
    onEdit?: (ac: AccessCode) => void
}
```

<img width="1572" alt="Screen Shot 2023-06-30 at 5 08 40 PM" src="https://github.com/seamapi/react/assets/1843707/842cb7b1-18bc-4e28-8ada-b643cf865a57">

[Link to figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=895-82543&mode=design&t=QauFhLYXHZwRHBJv-0)

Timezone for the start and end time will be set to local time by default.

We can use a lightweight date and time pickers library for selecting time, will have to see if we can inject custom timezones with it. Open to suggestions on what to use here.

### `<AccessCodeDetails />`:
![Image](https://github.com/seamapi/react/assets/1843707/95294789-ae7a-479b-a1d9-27c7468d70f6)

[Link to figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=842-76549&mode=design&t=QauFhLYXHZwRHBJv-0)

### `<AccessCodeTable />`:

![Image](https://github.com/seamapi/react/assets/1843707/b432f873-f67d-4030-9129-4fa11162c2e5)

[Link to figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=895-80211&mode=design&t=QauFhLYXHZwRHBJv-0)

![Image](https://github.com/seamapi/react/assets/1843707/4f4ffcd5-9054-416c-b32e-62d0b6269299)

[Link to figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=844-79041&mode=design&t=QauFhLYXHZwRHBJv-0)

**Comment by razor-x** [comment]
Current stance taken by this project is we are not adding MUI  as a dependency.

**Comment by dawnho** [comment]
@mikewuu this is ready to be tackled next. I'd love your input on what lightweight date time picker we could use here.

**Comment by mikewuu** [comment]
> [...] I'd love your input on what lightweight date time picker we could use here.

I've mostly used MUI, and jquery / bootstrap pickers before that.

Since we're not using MUI in the project, and jquery is hardly lightweight, we'll need to find an alternative.

A couple lightweight alternatives

- flatpickr ~30kb
- pikaday ~5kb



![Image](https://github.com/seamapi/react/assets/11449462/2b0c210a-030d-4a82-9ce3-6ff3a9b38925)

https://npmtrends.com/@mui/x-date-pickers-vs-bootstrap-datepicker-vs-flatpickr-vs-jquery-ui-vs-pikaday

### [flatpickr](https://github.com/flatpickr/flatpickr)

![Image](https://github.com/seamapi/react/assets/11449462/9a53bb29-5c2b-4df9-8fbc-43b347fbe042)

- ✅ More actively maintained (sep, 2022)

- ✅  More options, specifically, it has the ability to jump to a month/year

![Image](https://github.com/seamapi/react/assets/11449462/98847960-35c6-4ab3-a6ef-532373996458)

*pikaday doesn't have the ability to jump to a month/year like flatpickr (and MUI)*

- ⚠️ Relatively larger compared to pikaday (30kb vs 5kb)

![Image](https://github.com/seamapi/react/assets/11449462/fed35fa6-9954-425b-9805-ab2240cb5eee)

*not a huge library as the chart shows, but still, 6x bigger than pikaday*


### [pikaday](https://github.com/Pikaday/Pikaday)


![Image](https://github.com/seamapi/react/assets/11449462/9c3acbd8-d34b-42ad-ac0a-99beb99f8541)


- ✅ Lightweight 5kb (minified), date picking only (all we really need)

- ⚠️ Not able to match MUI features exactly. Lacks ability to jump to month/year.

- ⚠️ Not as actively maintained (last release was Oct, 2020)

**Comment by mikewuu** [comment]
@dawnho @razor-x  @seveibar do we have a preferred date picker here?

**Comment by razor-x** [comment]
Flatpickr looks like a good find. It's written in TS with zero dependencies. Does it have any support for style customization?

**Comment by mikewuu** [comment]
> Does it have any support for style customization?

Not out the box, no. And no support  for sass/scss 😞.

They have a couple [pre-built themes](https://flatpickr.js.org/themes/). We could probably just override (`!important`) the css for any minor adjustments.

If we wanted a fully custom theme, we might need to build our own though. It doesn't look too complicated: [example airbnb theme file](https://github.com/flatpickr/flatpickr/blob/master/src/style/themes/airbnb.styl).

**Comment by razor-x** [comment]
I just tried this on and it opened my native date picker. In my opinion that's a real feature (I'm guessing that's not too difficult to do in general but it's nice that that's its default behavior).

**Comment by razor-x** [comment]
I think we could start with this using zero customization and implement the rest of the UI.  That unblocks most of the implementation. Consider wrapping the picker in our own component so changing it out or customizing simpler.

**Comment by razor-x** [comment]
I think we could start with this using zero customization and implement the rest of the UI.  That unblocks most of the implementation. Consider wrapping the picker in our own component so changing it out or customizing simpler.

**Comment by razor-x** [comment]
For all the date stuff, keep using Luxon instead of Date. We may eventually replace luxin with a different smaller lib, but for now as long as we have it let's use it consistently.

**Comment by mikewuu** [comment]
Sounds good, thanks!

**Comment by razor-x** [comment]
Broke this up into smaller features:

- https://github.com/seamapi/react/issues/276
- https://github.com/seamapi/react/issues/277
- https://github.com/seamapi/react/issues/278
- https://github.com/seamapi/react/issues/279
